//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stage_Plan.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountStageplans = new HashSet<AccountStageplan>();
        }
    
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public string TempPassword { get; set; }
        public int VenueTemplateLimit { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime DateTokenCreated { get; set; }
        public string Token { get; set; }
        public int Iterations { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public System.DateTime DateAccountConfirmed { get; set; }
        public bool IsConfirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountStageplan> AccountStageplans { get; set; }
    }
}
