//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stage_Plan.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMapper
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int AccountStageplanId { get; set; }
    }
}
