

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Stage_plan.Dal
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StageplanEntities : DbContext
{
    public StageplanEntities()
        : base("name=StageplanEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Stageplan> Stageplans { get; set; }

    public virtual DbSet<StageplanInstrument> StageplanInstruments { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<MailingList> MailingLists { get; set; }

}

}

