//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stage_plan.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageplanInstrument
    {
        public int Id { get; set; }
        public int StageplanId { get; set; }
        public string InstrumentName { get; set; }
        public string Details { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public string DataHelper { get; set; }
        public string DataText { get; set; }
    
        public virtual Stageplan Stageplan { get; set; }
    }
}
