//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stage_Plan.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageplanInstrument
    {
        public int Id { get; set; }
        public int StageplanId { get; set; }
        public string DataDetail { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public string DataText { get; set; }
        public string Src { get; set; }
        public string BandMember { get; set; }
        public bool IsFixedPosition { get; set; }
        public string SelectedInstrument { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public int Zindex { get; set; }
        public int RotateAngle { get; set; }
    
        public virtual Stageplan Stageplan { get; set; }
    }
}
