//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stage_Plan.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stageplan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stageplan()
        {
            this.StageplanInstruments = new HashSet<StageplanInstrument>();
        }
    
        public int Id { get; set; }
        public string BandName { get; set; }
        public string Token { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int SavedByAccountId { get; set; }
        public string Website { get; set; }
        public string SocialMedia { get; set; }
        public string Genre { get; set; }
        public bool IsDeprecated { get; set; }
        public string Country { get; set; }
        public bool WillShowInRecentBands { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StageplanInstrument> StageplanInstruments { get; set; }
    }
}
